appName: ingest_app
logLevel: INFO
CONFIG:
  APP_CONFIG_DIR: "APP_ROOT_DIR/cfg"
  APP_LOG_DIR: "APP_ROOT_DIR/log"
  APP_DATA_IN_DIR: "NAS_ROOT_DIR/data/in"
  APP_DATA_OUT_DIR: "NAS_ROOT_DIR/data/out"
  APP_SQL_SCRIPT_DIR: "APP_ROOT_DIR/sql"
  APP_IMG_OUT_DIR: "NAS_ROOT_DIR/plot"
  # HIVE_WAREHOUSE_DIR_OLD: "APP_ROOT_DIR/data/user/hive/warehouse"
  # HIVE_WAREHOUSE_DIR: "APP_ROOT_DIR/spark-warehouse"
  HIVE_WAREHOUSE_DIR: "NAS_ROOT_DIR/datalake/user/hive/warehouse"
